package com.inmaa.admin.persistence;
// Generated 29 mai 2016 20:24:44 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Config generated by hbm2java
 */
@Entity
@Table(name = "config", catalog = "inmaa")
public class Config implements java.io.Serializable {

	private Integer configId;
	private String configImgpath;
	private String configEmailList;
	private String configIntroInma;
	private String configIntroMaamoura;
	private String configInmaGoal;
	private Integer configNbrVisite;
	private String configPrincipalEmail;
	private String configSmtpHost;
	private String configSmtpPort;
	private String configSmtpUser;
	private String configSmtpPwd;

	public Config() {
	}

	public Config(String configImgpath, String configPrincipalEmail, String configSmtpHost, String configSmtpPort,
			String configSmtpUser, String configSmtpPwd) {
		this.configImgpath = configImgpath;
		this.configPrincipalEmail = configPrincipalEmail;
		this.configSmtpHost = configSmtpHost;
		this.configSmtpPort = configSmtpPort;
		this.configSmtpUser = configSmtpUser;
		this.configSmtpPwd = configSmtpPwd;
	}

	public Config(String configImgpath, String configEmailList, String configIntroInma, String configIntroMaamoura,
			String configInmaGoal, Integer configNbrVisite, String configPrincipalEmail, String configSmtpHost,
			String configSmtpPort, String configSmtpUser, String configSmtpPwd) {
		this.configImgpath = configImgpath;
		this.configEmailList = configEmailList;
		this.configIntroInma = configIntroInma;
		this.configIntroMaamoura = configIntroMaamoura;
		this.configInmaGoal = configInmaGoal;
		this.configNbrVisite = configNbrVisite;
		this.configPrincipalEmail = configPrincipalEmail;
		this.configSmtpHost = configSmtpHost;
		this.configSmtpPort = configSmtpPort;
		this.configSmtpUser = configSmtpUser;
		this.configSmtpPwd = configSmtpPwd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Config_Id", unique = true, nullable = false)
	public Integer getConfigId() {
		return this.configId;
	}

	public void setConfigId(Integer configId) {
		this.configId = configId;
	}

	@Column(name = "config_Imgpath", nullable = false)
	public String getConfigImgpath() {
		return this.configImgpath;
	}

	public void setConfigImgpath(String configImgpath) {
		this.configImgpath = configImgpath;
	}

	@Column(name = "config_EmailList", length = 65535)
	public String getConfigEmailList() {
		return this.configEmailList;
	}

	public void setConfigEmailList(String configEmailList) {
		this.configEmailList = configEmailList;
	}

	@Column(name = "config_IntroInma", length = 65535)
	public String getConfigIntroInma() {
		return this.configIntroInma;
	}

	public void setConfigIntroInma(String configIntroInma) {
		this.configIntroInma = configIntroInma;
	}

	@Column(name = "config_IntroMaamoura", length = 65535)
	public String getConfigIntroMaamoura() {
		return this.configIntroMaamoura;
	}

	public void setConfigIntroMaamoura(String configIntroMaamoura) {
		this.configIntroMaamoura = configIntroMaamoura;
	}

	@Column(name = "config_Inma_Goal", length = 65535)
	public String getConfigInmaGoal() {
		return this.configInmaGoal;
	}

	public void setConfigInmaGoal(String configInmaGoal) {
		this.configInmaGoal = configInmaGoal;
	}

	@Column(name = "config_NbrVisite")
	public Integer getConfigNbrVisite() {
		return this.configNbrVisite;
	}

	public void setConfigNbrVisite(Integer configNbrVisite) {
		this.configNbrVisite = configNbrVisite;
	}

	@Column(name = "config_PrincipalEmail", nullable = false, length = 100)
	public String getConfigPrincipalEmail() {
		return this.configPrincipalEmail;
	}

	public void setConfigPrincipalEmail(String configPrincipalEmail) {
		this.configPrincipalEmail = configPrincipalEmail;
	}

	@Column(name = "config_smtpHost", nullable = false, length = 45)
	public String getConfigSmtpHost() {
		return this.configSmtpHost;
	}

	public void setConfigSmtpHost(String configSmtpHost) {
		this.configSmtpHost = configSmtpHost;
	}

	@Column(name = "config_smtpPort", nullable = false, length = 45)
	public String getConfigSmtpPort() {
		return this.configSmtpPort;
	}

	public void setConfigSmtpPort(String configSmtpPort) {
		this.configSmtpPort = configSmtpPort;
	}

	@Column(name = "config_smtpUser", nullable = false, length = 100)
	public String getConfigSmtpUser() {
		return this.configSmtpUser;
	}

	public void setConfigSmtpUser(String configSmtpUser) {
		this.configSmtpUser = configSmtpUser;
	}

	@Column(name = "config_smtpPwd", nullable = false, length = 60)
	public String getConfigSmtpPwd() {
		return this.configSmtpPwd;
	}

	public void setConfigSmtpPwd(String configSmtpPwd) {
		this.configSmtpPwd = configSmtpPwd;
	}

}
