package com.inmaa.admin.persistence;
// Generated 22 nov. 2015 14:53:17 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Config generated by hbm2java
 */
@Entity
@Table(name = "config", catalog = "inmaa")
public class Config implements java.io.Serializable {

	private Integer configId;
	private String configImgpath;
	private String configEmailList;

	public Config() {
	}

	public Config(String configImgpath) {
		this.configImgpath = configImgpath;
	}

	public Config(String configImgpath, String configEmailList) {
		this.configImgpath = configImgpath;
		this.configEmailList = configEmailList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Config_Id", unique = true, nullable = false)
	public Integer getConfigId() {
		return this.configId;
	}

	public void setConfigId(Integer configId) {
		this.configId = configId;
	}

	@Column(name = "config_Imgpath", nullable = false)
	public String getConfigImgpath() {
		return this.configImgpath;
	}

	public void setConfigImgpath(String configImgpath) {
		this.configImgpath = configImgpath;
	}

	@Column(name = "config_EmailList", length = 65535)
	public String getConfigEmailList() {
		return this.configEmailList;
	}

	public void setConfigEmailList(String configEmailList) {
		this.configEmailList = configEmailList;
	}

}
