package com.inmaa.admin.persistence;
// Generated 5 juil. 2016 15:38:11 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "Contact", catalog = "inmaa")
public class Contact implements java.io.Serializable {

	private Integer contactId;
	private Integer seqNo;
	private String contactName;
	private String contactName1;
	private String contactFunction;
	private String contactGsm1;
	private String contactGsm2;
	private String contactFax;
	private String contactEmail;
	private String contactAddress;
	private String contactType;
	private String contactWebSite;
	private String contactAutre;
	private String contactPicture;
	private Boolean contactGender;
	private Date contactBirthDay;

	public Contact() {
	}

	public Contact(Integer seqNo, String contactName, String contactName1, String contactFunction, String contactGsm1,
			String contactGsm2, String contactFax, String contactEmail, String contactAddress, String contactType,
			String contactWebSite, String contactAutre, String contactPicture, Boolean contactGender,
			Date contactBirthDay) {
		this.seqNo = seqNo;
		this.contactName = contactName;
		this.contactName1 = contactName1;
		this.contactFunction = contactFunction;
		this.contactGsm1 = contactGsm1;
		this.contactGsm2 = contactGsm2;
		this.contactFax = contactFax;
		this.contactEmail = contactEmail;
		this.contactAddress = contactAddress;
		this.contactType = contactType;
		this.contactWebSite = contactWebSite;
		this.contactAutre = contactAutre;
		this.contactPicture = contactPicture;
		this.contactGender = contactGender;
		this.contactBirthDay = contactBirthDay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Contact_id", unique = true, nullable = false)
	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Contact_Name", length = 80)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "Contact_Name1", length = 100)
	public String getContactName1() {
		return this.contactName1;
	}

	public void setContactName1(String contactName1) {
		this.contactName1 = contactName1;
	}

	@Column(name = "Contact_Function", length = 80)
	public String getContactFunction() {
		return this.contactFunction;
	}

	public void setContactFunction(String contactFunction) {
		this.contactFunction = contactFunction;
	}

	@Column(name = "Contact_GSM1", length = 40)
	public String getContactGsm1() {
		return this.contactGsm1;
	}

	public void setContactGsm1(String contactGsm1) {
		this.contactGsm1 = contactGsm1;
	}

	@Column(name = "Contact_GSM2", length = 40)
	public String getContactGsm2() {
		return this.contactGsm2;
	}

	public void setContactGsm2(String contactGsm2) {
		this.contactGsm2 = contactGsm2;
	}

	@Column(name = "Contact_Fax", length = 40)
	public String getContactFax() {
		return this.contactFax;
	}

	public void setContactFax(String contactFax) {
		this.contactFax = contactFax;
	}

	@Column(name = "Contact_EMAIL", length = 100)
	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	@Column(name = "Contact_Address", length = 200)
	public String getContactAddress() {
		return this.contactAddress;
	}

	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	@Column(name = "Contact_Type", length = 90)
	public String getContactType() {
		return this.contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	@Column(name = "Contact_WebSite", length = 80)
	public String getContactWebSite() {
		return this.contactWebSite;
	}

	public void setContactWebSite(String contactWebSite) {
		this.contactWebSite = contactWebSite;
	}

	@Column(name = "Contact_Autre", length = 150)
	public String getContactAutre() {
		return this.contactAutre;
	}

	public void setContactAutre(String contactAutre) {
		this.contactAutre = contactAutre;
	}

	@Column(name = "Contact_Picture", length = 60)
	public String getContactPicture() {
		return this.contactPicture;
	}

	public void setContactPicture(String contactPicture) {
		this.contactPicture = contactPicture;
	}

	@Column(name = "Contact_Gender")
	public Boolean getContactGender() {
		return this.contactGender;
	}

	public void setContactGender(Boolean contactGender) {
		this.contactGender = contactGender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Contact_BirthDay", length = 10)
	public Date getContactBirthDay() {
		return this.contactBirthDay;
	}

	public void setContactBirthDay(Date contactBirthDay) {
		this.contactBirthDay = contactBirthDay;
	}

}
