package com.inmaa.admin.persistence;

// Generated 9 juil. 2015 19:09:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "Event", catalog = "inmaa")
public class Event implements java.io.Serializable {

	private Integer eventId;
	private Integer seqNo;
	private String eventName;
	private String eventDesc;
	private Date eventStartDate;
	private Date eventEndDate;
	private Set<Project> projects = new HashSet<Project>(0);

	public Event() {
	}

	public Event(Integer seqNo, String eventName, String eventDesc,
			Date eventStartDate, Date eventEndDate, Set<Project> projects) {
		this.seqNo = seqNo;
		this.eventName = eventName;
		this.eventDesc = eventDesc;
		this.eventStartDate = eventStartDate;
		this.eventEndDate = eventEndDate;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Event_ID", unique = true, nullable = false)
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Event_Name")
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "Event_Desc")
	public String getEventDesc() {
		return this.eventDesc;
	}

	public void setEventDesc(String eventDesc) {
		this.eventDesc = eventDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Event_StartDate", length = 10)
	public Date getEventStartDate() {
		return this.eventStartDate;
	}

	public void setEventStartDate(Date eventStartDate) {
		this.eventStartDate = eventStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Event_EndDate", length = 10)
	public Date getEventEndDate() {
		return this.eventEndDate;
	}

	public void setEventEndDate(Date eventEndDate) {
		this.eventEndDate = eventEndDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Event_Project", catalog = "inmaa", joinColumns = { @JoinColumn(name = "Event_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Project_ID", nullable = false, updatable = false) })
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
