package com.inmaa.admin.persistence;
// Generated 28 nov. 2015 18:12:17 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "Partner", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = "Partner_Name") )
public class Partner implements java.io.Serializable {

	private Integer partnerId;
	private Integer seqNo;
	private String partnerName;
	private String partnerPlace;
	private Date partnerStartDate;
	private String partnerDesc;
	private String partnerLogo;
	private Boolean partnerType;

	public Partner() {
	}

	public Partner(String partnerName, String partnerPlace, String partnerLogo) {
		this.partnerName = partnerName;
		this.partnerPlace = partnerPlace;
		this.partnerLogo = partnerLogo;
	}

	public Partner(Integer seqNo, String partnerName, String partnerPlace, Date partnerStartDate, String partnerDesc,
			String partnerLogo, Boolean partnerType) {
		this.seqNo = seqNo;
		this.partnerName = partnerName;
		this.partnerPlace = partnerPlace;
		this.partnerStartDate = partnerStartDate;
		this.partnerDesc = partnerDesc;
		this.partnerLogo = partnerLogo;
		this.partnerType = partnerType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Partner_ID", unique = true, nullable = false)
	public Integer getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(Integer partnerId) {
		this.partnerId = partnerId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Partner_Name", unique = true, nullable = false, length = 45)
	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	@Column(name = "Partner_Place", nullable = false, length = 45)
	public String getPartnerPlace() {
		return this.partnerPlace;
	}

	public void setPartnerPlace(String partnerPlace) {
		this.partnerPlace = partnerPlace;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Partner_StartDate", length = 10)
	public Date getPartnerStartDate() {
		return this.partnerStartDate;
	}

	public void setPartnerStartDate(Date partnerStartDate) {
		this.partnerStartDate = partnerStartDate;
	}

	@Column(name = "Partner_Desc", length = 16777215)
	public String getPartnerDesc() {
		return this.partnerDesc;
	}

	public void setPartnerDesc(String partnerDesc) {
		this.partnerDesc = partnerDesc;
	}

	@Column(name = "Partner_Logo", nullable = false, length = 45)
	public String getPartnerLogo() {
		return this.partnerLogo;
	}

	public void setPartnerLogo(String partnerLogo) {
		this.partnerLogo = partnerLogo;
	}

	@Column(name = "Partner_Type")
	public Boolean getPartnerType() {
		return this.partnerType;
	}

	public void setPartnerType(Boolean partnerType) {
		this.partnerType = partnerType;
	}

}
