package com.inmaa.admin.persistence;

// Generated 29 août 2015 14:30:32 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "News", catalog = "inmaa")
public class News implements java.io.Serializable {

	private Integer newsId;
	private String newsDesc;
	private String newsDesc1;
	private String newsTitle;
	private String newsSource;
	private Integer seqNo;
	private Set<Project> projects = new HashSet<Project>(0);

	public News() {
	}

	public News(String newsDesc, String newsDesc1, String newsTitle,
			String newsSource, Integer seqNo, Set<Project> projects) {
		this.newsDesc = newsDesc;
		this.newsDesc1 = newsDesc1;
		this.newsTitle = newsTitle;
		this.newsSource = newsSource;
		this.seqNo = seqNo;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "News_ID", unique = true, nullable = false)
	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	@Column(name = "News_Desc")
	public String getNewsDesc() {
		return this.newsDesc;
	}

	public void setNewsDesc(String newsDesc) {
		this.newsDesc = newsDesc;
	}

	@Column(name = "News_Desc1")
	public String getNewsDesc1() {
		return this.newsDesc1;
	}

	public void setNewsDesc1(String newsDesc1) {
		this.newsDesc1 = newsDesc1;
	}

	@Column(name = "News_Title")
	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	@Column(name = "News_Source")
	public String getNewsSource() {
		return this.newsSource;
	}

	public void setNewsSource(String newsSource) {
		this.newsSource = newsSource;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "News_Project", catalog = "inmaa", joinColumns = { @JoinColumn(name = "News_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Projects_ID", nullable = false, updatable = false) })
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
