package com.inmaa.admin.persistence;

// Generated 29 août 2015 14:30:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project", catalog = "inmaa")
public class Project implements java.io.Serializable {

	private Integer projectId;
	private Integer seqNo;
	private String projectLogo;
	private String projectDesc;
	private String projectName;
	private Date projectStartDate;
	private Set<Event> events = new HashSet<Event>(0);
	private Set<News> newses = new HashSet<News>(0);
	private Set<Member> members = new HashSet<Member>(0);

	public Project() {
	}

	public Project(Integer seqNo, String projectLogo, String projectDesc,
			String projectName, Date projectStartDate, Set<Event> events,
			Set<News> newses, Set<Member> members) {
		this.seqNo = seqNo;
		this.projectLogo = projectLogo;
		this.projectDesc = projectDesc;
		this.projectName = projectName;
		this.projectStartDate = projectStartDate;
		this.events = events;
		this.newses = newses;
		this.members = members;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Project_ID", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Project_Logo")
	public String getProjectLogo() {
		return this.projectLogo;
	}

	public void setProjectLogo(String projectLogo) {
		this.projectLogo = projectLogo;
	}

	@Column(name = "Project_Desc")
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Column(name = "Project_Name")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Project_StartDate", length = 10)
	public Date getProjectStartDate() {
		return this.projectStartDate;
	}

	public void setProjectStartDate(Date projectStartDate) {
		this.projectStartDate = projectStartDate;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Project_Member", catalog = "inmaa", joinColumns = { @JoinColumn(name = "Project_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Member_ID", nullable = false, updatable = false) })
	public Set<Member> getMembers() {
		return this.members;
	}

	public void setMembers(Set<Member> members) {
		this.members = members;
	}

}
