package com.inmaa.admin.persistence;
// Generated 19 juin 2016 15:54:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Abonnement generated by hbm2java
 */
@Entity
@Table(name = "Abonnement", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = { "Abonnement_Year",
		"Abonnement_MemberID" }) )
public class Abonnement implements java.io.Serializable {

	private Integer abonnementId;
	private Member member;
	private float abonnementAmount;
	private int abonnementYear;

	public Abonnement() {
	}

	public Abonnement(Member member, float abonnementAmount, int abonnementYear) {
		this.member = member;
		this.abonnementAmount = abonnementAmount;
		this.abonnementYear = abonnementYear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Abonnement_ID", unique = true, nullable = false)
	public Integer getAbonnementId() {
		return this.abonnementId;
	}

	public void setAbonnementId(Integer abonnementId) {
		this.abonnementId = abonnementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Abonnement_MemberID", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "Abonnement_Amount", nullable = false, precision = 12, scale = 0)
	public float getAbonnementAmount() {
		return this.abonnementAmount;
	}

	public void setAbonnementAmount(float abonnementAmount) {
		this.abonnementAmount = abonnementAmount;
	}

	@Column(name = "Abonnement_Year", nullable = false)
	public int getAbonnementYear() {
		return this.abonnementYear;
	}

	public void setAbonnementYear(int abonnementYear) {
		this.abonnementYear = abonnementYear;
	}

}
