package com.inmaa.admin.persistence;
// Generated 28 févr. 2016 21:48:16 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Config generated by hbm2java
 */
@Entity
@Table(name = "config", catalog = "inmaa")
public class Config implements java.io.Serializable {

	private Integer configId;
	private String configImgpath;
	private String configEmailList;
	private String configIntroInma;
	private String configIntroMaamoura;
	private String configInmaGoal;

	public Config() {
	}

	public Config(String configImgpath) {
		this.configImgpath = configImgpath;
	}

	public Config(String configImgpath, String configEmailList, String configIntroInma, String configIntroMaamoura,
			String configInmaGoal) {
		this.configImgpath = configImgpath;
		this.configEmailList = configEmailList;
		this.configIntroInma = configIntroInma;
		this.configIntroMaamoura = configIntroMaamoura;
		this.configInmaGoal = configInmaGoal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Config_Id", unique = true, nullable = false)
	public Integer getConfigId() {
		return this.configId;
	}

	public void setConfigId(Integer configId) {
		this.configId = configId;
	}

	@Column(name = "config_Imgpath", nullable = false)
	public String getConfigImgpath() {
		return this.configImgpath;
	}

	public void setConfigImgpath(String configImgpath) {
		this.configImgpath = configImgpath;
	}

	@Column(name = "config_EmailList", length = 65535)
	public String getConfigEmailList() {
		return this.configEmailList;
	}

	public void setConfigEmailList(String configEmailList) {
		this.configEmailList = configEmailList;
	}

	@Column(name = "config_IntroInma", length = 65535)
	public String getConfigIntroInma() {
		return this.configIntroInma;
	}

	public void setConfigIntroInma(String configIntroInma) {
		this.configIntroInma = configIntroInma;
	}

	@Column(name = "config_IntroMaamoura", length = 65535)
	public String getConfigIntroMaamoura() {
		return this.configIntroMaamoura;
	}

	public void setConfigIntroMaamoura(String configIntroMaamoura) {
		this.configIntroMaamoura = configIntroMaamoura;
	}

	@Column(name = "config_Inma_Goal", length = 65535)
	public String getConfigInmaGoal() {
		return this.configInmaGoal;
	}

	public void setConfigInmaGoal(String configInmaGoal) {
		this.configInmaGoal = configInmaGoal;
	}

}
