package com.inmaa.admin.persistence;

// Generated 29 oct. 2015 21:42:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "Media", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = "Media_Name"))
public class Media implements java.io.Serializable {

	private int mediaId;
	private String mediaName;
	private Date mediaDate;
	private String mediaLocation;
	private String mediaCollection;

	public Media() {
	}

	public Media(int mediaId, String mediaName, Date mediaDate,
			String mediaLocation, String mediaCollection) {
		this.mediaId = mediaId;
		this.mediaName = mediaName;
		this.mediaDate = mediaDate;
		this.mediaLocation = mediaLocation;
		this.mediaCollection = mediaCollection;
	}

	@Id
	@Column(name = "Media_Id", unique = true, nullable = false)
	public int getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(int mediaId) {
		this.mediaId = mediaId;
	}

	@Column(name = "Media_Name", unique = true, nullable = false, length = 45)
	public String getMediaName() {
		return this.mediaName;
	}

	public void setMediaName(String mediaName) {
		this.mediaName = mediaName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Media_Date", nullable = false, length = 10)
	public Date getMediaDate() {
		return this.mediaDate;
	}

	public void setMediaDate(Date mediaDate) {
		this.mediaDate = mediaDate;
	}

	@Column(name = "Media_Location", nullable = false, length = 45)
	public String getMediaLocation() {
		return this.mediaLocation;
	}

	public void setMediaLocation(String mediaLocation) {
		this.mediaLocation = mediaLocation;
	}

	@Column(name = "Media_Collection", nullable = false, length = 65535)
	public String getMediaCollection() {
		return this.mediaCollection;
	}

	public void setMediaCollection(String mediaCollection) {
		this.mediaCollection = mediaCollection;
	}

}
