package com.inmaa.admin.persistence;
// Generated 19 juin 2016 15:54:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "Member", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = { "Member_Name",
		"Member_Name1" }) )
public class Member implements java.io.Serializable {

	private Integer memberId;
	private Integer seqNo;
	private String memberName;
	private String memberName1;
	private String memberStatus;
	private int memberAge;
	private boolean memberIsOrg;
	private String memberTravail;
	private String memberImage;
	private String memberFacebook;
	private String memberTwitter;
	private Date memberBirthDay;
	private Integer memberCin;
	private String memberNationality;
	private String memberPhone;
	private String memberEmail;
	private String memberAddress;
	private String memberCity;
	private Boolean isActive;
	private Boolean memberGender;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Abonnement> abonnements = new HashSet<Abonnement>(0);

	public Member() {
	}

	public Member(String memberName, String memberName1, int memberAge, boolean memberIsOrg, Date memberBirthDay,
			String memberPhone, String memberEmail, String memberCity) {
		this.memberName = memberName;
		this.memberName1 = memberName1;
		this.memberAge = memberAge;
		this.memberIsOrg = memberIsOrg;
		this.memberBirthDay = memberBirthDay;
		this.memberPhone = memberPhone;
		this.memberEmail = memberEmail;
		this.memberCity = memberCity;
	}

	public Member(Integer seqNo, String memberName, String memberName1, String memberStatus, int memberAge,
			boolean memberIsOrg, String memberTravail, String memberImage, String memberFacebook, String memberTwitter,
			Date memberBirthDay, Integer memberCin, String memberNationality, String memberPhone, String memberEmail,
			String memberAddress, String memberCity, Boolean isActive, Boolean memberGender, Set<Project> projects,
			Set<Event> events, Set<Abonnement> abonnements) {
		this.seqNo = seqNo;
		this.memberName = memberName;
		this.memberName1 = memberName1;
		this.memberStatus = memberStatus;
		this.memberAge = memberAge;
		this.memberIsOrg = memberIsOrg;
		this.memberTravail = memberTravail;
		this.memberImage = memberImage;
		this.memberFacebook = memberFacebook;
		this.memberTwitter = memberTwitter;
		this.memberBirthDay = memberBirthDay;
		this.memberCin = memberCin;
		this.memberNationality = memberNationality;
		this.memberPhone = memberPhone;
		this.memberEmail = memberEmail;
		this.memberAddress = memberAddress;
		this.memberCity = memberCity;
		this.isActive = isActive;
		this.memberGender = memberGender;
		this.projects = projects;
		this.events = events;
		this.abonnements = abonnements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Member_ID", unique = true, nullable = false)
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Member_Name", nullable = false)
	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	@Column(name = "Member_Name1", nullable = false)
	public String getMemberName1() {
		return this.memberName1;
	}

	public void setMemberName1(String memberName1) {
		this.memberName1 = memberName1;
	}

	@Column(name = "Member_Status")
	public String getMemberStatus() {
		return this.memberStatus;
	}

	public void setMemberStatus(String memberStatus) {
		this.memberStatus = memberStatus;
	}

	@Column(name = "Member_Age", nullable = false)
	public int getMemberAge() {
		return this.memberAge;
	}

	public void setMemberAge(int memberAge) {
		this.memberAge = memberAge;
	}

	@Column(name = "Member_IsOrg", nullable = false)
	public boolean isMemberIsOrg() {
		return this.memberIsOrg;
	}

	public void setMemberIsOrg(boolean memberIsOrg) {
		this.memberIsOrg = memberIsOrg;
	}

	@Column(name = "Member_Travail")
	public String getMemberTravail() {
		return this.memberTravail;
	}

	public void setMemberTravail(String memberTravail) {
		this.memberTravail = memberTravail;
	}

	@Column(name = "Member_Image", length = 45)
	public String getMemberImage() {
		return this.memberImage;
	}

	public void setMemberImage(String memberImage) {
		this.memberImage = memberImage;
	}

	@Column(name = "Member_facebook", length = 45)
	public String getMemberFacebook() {
		return this.memberFacebook;
	}

	public void setMemberFacebook(String memberFacebook) {
		this.memberFacebook = memberFacebook;
	}

	@Column(name = "Member_twitter", length = 45)
	public String getMemberTwitter() {
		return this.memberTwitter;
	}

	public void setMemberTwitter(String memberTwitter) {
		this.memberTwitter = memberTwitter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Member_BirthDay", nullable = false, length = 10)
	public Date getMemberBirthDay() {
		return this.memberBirthDay;
	}

	public void setMemberBirthDay(Date memberBirthDay) {
		this.memberBirthDay = memberBirthDay;
	}

	@Column(name = "Member_CIN")
	public Integer getMemberCin() {
		return this.memberCin;
	}

	public void setMemberCin(Integer memberCin) {
		this.memberCin = memberCin;
	}

	@Column(name = "Member_Nationality", length = 45)
	public String getMemberNationality() {
		return this.memberNationality;
	}

	public void setMemberNationality(String memberNationality) {
		this.memberNationality = memberNationality;
	}

	@Column(name = "Member_Phone", nullable = false, length = 45)
	public String getMemberPhone() {
		return this.memberPhone;
	}

	public void setMemberPhone(String memberPhone) {
		this.memberPhone = memberPhone;
	}

	@Column(name = "Member_Email", nullable = false, length = 45)
	public String getMemberEmail() {
		return this.memberEmail;
	}

	public void setMemberEmail(String memberEmail) {
		this.memberEmail = memberEmail;
	}

	@Column(name = "Member_Address", length = 45)
	public String getMemberAddress() {
		return this.memberAddress;
	}

	public void setMemberAddress(String memberAddress) {
		this.memberAddress = memberAddress;
	}

	@Column(name = "Member_City", nullable = false, length = 45)
	public String getMemberCity() {
		return this.memberCity;
	}

	public void setMemberCity(String memberCity) {
		this.memberCity = memberCity;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Member_Gender")
	public Boolean getMemberGender() {
		return this.memberGender;
	}

	public void setMemberGender(Boolean memberGender) {
		this.memberGender = memberGender;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "members")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "member")
	public Set<Abonnement> getAbonnements() {
		return this.abonnements;
	}

	public void setAbonnements(Set<Abonnement> abonnements) {
		this.abonnements = abonnements;
	}

}
