package com.inmaa.admin.persistence;

// Generated 27 oct. 2015 18:27:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "News", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = "News_Title"))
public class News implements java.io.Serializable {

	private Integer newsId;
	private String newsDesc;
	private String newsDesc1;
	private String newsTitle;
	private String newsSource;
	private Integer seqNo;
	private String newsAuthor;
	private Date newsDate;
	private String newsPicture;
	private Set<Project> projects = new HashSet<Project>(0);

	public News() {
	}

	public News(String newsDesc, String newsTitle, String newsAuthor,
			Date newsDate, String newsPicture) {
		this.newsDesc = newsDesc;
		this.newsTitle = newsTitle;
		this.newsAuthor = newsAuthor;
		this.newsDate = newsDate;
		this.newsPicture = newsPicture;
	}

	public News(String newsDesc, String newsDesc1, String newsTitle,
			String newsSource, Integer seqNo, String newsAuthor, Date newsDate,
			String newsPicture, Set<Project> projects) {
		this.newsDesc = newsDesc;
		this.newsDesc1 = newsDesc1;
		this.newsTitle = newsTitle;
		this.newsSource = newsSource;
		this.seqNo = seqNo;
		this.newsAuthor = newsAuthor;
		this.newsDate = newsDate;
		this.newsPicture = newsPicture;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "News_ID", unique = true, nullable = false)
	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	@Column(name = "News_Desc", nullable = false)
	public String getNewsDesc() {
		return this.newsDesc;
	}

	public void setNewsDesc(String newsDesc) {
		this.newsDesc = newsDesc;
	}

	@Column(name = "News_Desc1")
	public String getNewsDesc1() {
		return this.newsDesc1;
	}

	public void setNewsDesc1(String newsDesc1) {
		this.newsDesc1 = newsDesc1;
	}

	@Column(name = "News_Title", unique = true, nullable = false)
	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	@Column(name = "News_Source")
	public String getNewsSource() {
		return this.newsSource;
	}

	public void setNewsSource(String newsSource) {
		this.newsSource = newsSource;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "News_Author", nullable = false, length = 45)
	public String getNewsAuthor() {
		return this.newsAuthor;
	}

	public void setNewsAuthor(String newsAuthor) {
		this.newsAuthor = newsAuthor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "News_Date", nullable = false, length = 10)
	public Date getNewsDate() {
		return this.newsDate;
	}

	public void setNewsDate(Date newsDate) {
		this.newsDate = newsDate;
	}

	@Column(name = "News_Picture", nullable = false)
	public String getNewsPicture() {
		return this.newsPicture;
	}

	public void setNewsPicture(String newsPicture) {
		this.newsPicture = newsPicture;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "News_Project", catalog = "inmaa", joinColumns = { @JoinColumn(name = "News_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Projects_ID", nullable = false, updatable = false) })
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
