package com.inmaa.admin.persistence;

// Generated 27 oct. 2015 18:27:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "Partner", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = "Partner_Name"))
public class Partner implements java.io.Serializable {

	private int partnerId;
	private Integer seqNo;
	private String partnerName;
	private String partnerPlace;
	private String partnerStartDate;
	private String partnerDesc;
	private String partnerLogo;

	public Partner() {
	}

	public Partner(int partnerId, String partnerName, String partnerPlace,
			String partnerLogo) {
		this.partnerId = partnerId;
		this.partnerName = partnerName;
		this.partnerPlace = partnerPlace;
		this.partnerLogo = partnerLogo;
	}

	public Partner(int partnerId, Integer seqNo, String partnerName,
			String partnerPlace, String partnerStartDate, String partnerDesc,
			String partnerLogo) {
		this.partnerId = partnerId;
		this.seqNo = seqNo;
		this.partnerName = partnerName;
		this.partnerPlace = partnerPlace;
		this.partnerStartDate = partnerStartDate;
		this.partnerDesc = partnerDesc;
		this.partnerLogo = partnerLogo;
	}

	@Id
	@Column(name = "Partner_ID", unique = true, nullable = false)
	public int getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(int partnerId) {
		this.partnerId = partnerId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Partner_Name", unique = true, nullable = false, length = 45)
	public String getPartnerName() {
		return this.partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	@Column(name = "Partner_Place", nullable = false, length = 45)
	public String getPartnerPlace() {
		return this.partnerPlace;
	}

	public void setPartnerPlace(String partnerPlace) {
		this.partnerPlace = partnerPlace;
	}

	@Column(name = "Partner_StartDate", length = 45)
	public String getPartnerStartDate() {
		return this.partnerStartDate;
	}

	public void setPartnerStartDate(String partnerStartDate) {
		this.partnerStartDate = partnerStartDate;
	}

	@Column(name = "Partner_Desc", length = 16777215)
	public String getPartnerDesc() {
		return this.partnerDesc;
	}

	public void setPartnerDesc(String partnerDesc) {
		this.partnerDesc = partnerDesc;
	}

	@Column(name = "Partner_Logo", nullable = false, length = 45)
	public String getPartnerLogo() {
		return this.partnerLogo;
	}

	public void setPartnerLogo(String partnerLogo) {
		this.partnerLogo = partnerLogo;
	}

}
