package com.inmaa.admin.persistence;
// Generated 25 déc. 2015 16:35:57 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = "Project_Name") )
public class Project implements java.io.Serializable {

	private Integer projectId;
	private Integer seqNo;
	private String projectLogo;
	private String projectDesc;
	private String projectName;
	private Date projectStartDate;
	private String projectLocation;
	private String projectPhone;
	private String projectPartner;
	private String projectDef;
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Article> articles = new HashSet<Article>(0);
	private Set<Member> members = new HashSet<Member>(0);

	public Project() {
	}

	public Project(String projectLogo, String projectDesc, String projectName, Date projectStartDate) {
		this.projectLogo = projectLogo;
		this.projectDesc = projectDesc;
		this.projectName = projectName;
		this.projectStartDate = projectStartDate;
	}

	public Project(Integer seqNo, String projectLogo, String projectDesc, String projectName, Date projectStartDate,
			String projectLocation, String projectPhone, String projectPartner, String projectDef, Set<Event> events,
			Set<Article> articles, Set<Member> members) {
		this.seqNo = seqNo;
		this.projectLogo = projectLogo;
		this.projectDesc = projectDesc;
		this.projectName = projectName;
		this.projectStartDate = projectStartDate;
		this.projectLocation = projectLocation;
		this.projectPhone = projectPhone;
		this.projectPartner = projectPartner;
		this.projectDef = projectDef;
		this.events = events;
		this.articles = articles;
		this.members = members;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Project_ID", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Project_Logo", nullable = false)
	public String getProjectLogo() {
		return this.projectLogo;
	}

	public void setProjectLogo(String projectLogo) {
		this.projectLogo = projectLogo;
	}

	@Column(name = "Project_Desc", nullable = false)
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Column(name = "Project_Name", unique = true, nullable = false)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Project_StartDate", nullable = false, length = 10)
	public Date getProjectStartDate() {
		return this.projectStartDate;
	}

	public void setProjectStartDate(Date projectStartDate) {
		this.projectStartDate = projectStartDate;
	}

	@Column(name = "Project_Location", length = 45)
	public String getProjectLocation() {
		return this.projectLocation;
	}

	public void setProjectLocation(String projectLocation) {
		this.projectLocation = projectLocation;
	}

	@Column(name = "Project_Phone", length = 45)
	public String getProjectPhone() {
		return this.projectPhone;
	}

	public void setProjectPhone(String projectPhone) {
		this.projectPhone = projectPhone;
	}

	@Column(name = "Project_partner", length = 90)
	public String getProjectPartner() {
		return this.projectPartner;
	}

	public void setProjectPartner(String projectPartner) {
		this.projectPartner = projectPartner;
	}

	@Column(name = "Project_Def", length = 16777215)
	public String getProjectDef() {
		return this.projectDef;
	}

	public void setProjectDef(String projectDef) {
		this.projectDef = projectDef;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Project_Member", catalog = "inmaa", joinColumns = {
			@JoinColumn(name = "Project_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Member_ID", nullable = false, updatable = false) })
	public Set<Member> getMembers() {
		return this.members;
	}

	public void setMembers(Set<Member> members) {
		this.members = members;
	}

}
