package com.inmaa.admin.persistence;
// Generated 22 janv. 2016 20:06:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Publication generated by hbm2java
 */
@Entity
@Table(name = "Publication", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = "Publication_Name") )
public class Publication implements java.io.Serializable {

	private Integer publicationId;
	private Integer seqNo;
	private String publicationName;
	private Date publicationDate;
	private String publicationLink;
	private String publicationUrl;
	private String publicationPicture;
	private String publicationDesc;
	private String publicationType;

	public Publication() {
	}

	public Publication(String publicationName, Date publicationDate) {
		this.publicationName = publicationName;
		this.publicationDate = publicationDate;
	}

	public Publication(Integer seqNo, String publicationName, Date publicationDate, String publicationLink,
			String publicationUrl, String publicationPicture, String publicationDesc, String publicationType) {
		this.seqNo = seqNo;
		this.publicationName = publicationName;
		this.publicationDate = publicationDate;
		this.publicationLink = publicationLink;
		this.publicationUrl = publicationUrl;
		this.publicationPicture = publicationPicture;
		this.publicationDesc = publicationDesc;
		this.publicationType = publicationType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Publication_Id", unique = true, nullable = false)
	public Integer getPublicationId() {
		return this.publicationId;
	}

	public void setPublicationId(Integer publicationId) {
		this.publicationId = publicationId;
	}

	@Column(name = "SeqNo")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Column(name = "Publication_Name", unique = true, nullable = false, length = 45)
	public String getPublicationName() {
		return this.publicationName;
	}

	public void setPublicationName(String publicationName) {
		this.publicationName = publicationName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Publication_Date", nullable = false, length = 10)
	public Date getPublicationDate() {
		return this.publicationDate;
	}

	public void setPublicationDate(Date publicationDate) {
		this.publicationDate = publicationDate;
	}

	@Column(name = "Publication_Link", length = 225)
	public String getPublicationLink() {
		return this.publicationLink;
	}

	public void setPublicationLink(String publicationLink) {
		this.publicationLink = publicationLink;
	}

	@Column(name = "Publication_Url", length = 450)
	public String getPublicationUrl() {
		return this.publicationUrl;
	}

	public void setPublicationUrl(String publicationUrl) {
		this.publicationUrl = publicationUrl;
	}

	@Column(name = "Publication_Picture", length = 80)
	public String getPublicationPicture() {
		return this.publicationPicture;
	}

	public void setPublicationPicture(String publicationPicture) {
		this.publicationPicture = publicationPicture;
	}

	@Column(name = "Publication_Desc", length = 65535)
	public String getPublicationDesc() {
		return this.publicationDesc;
	}

	public void setPublicationDesc(String publicationDesc) {
		this.publicationDesc = publicationDesc;
	}

	@Column(name = "Publication_Type", length = 4)
	public String getPublicationType() {
		return this.publicationType;
	}

	public void setPublicationType(String publicationType) {
		this.publicationType = publicationType;
	}

}
