package com.inmaa.admin.persistence;

// Generated 7 nov. 2015 10:51:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Publication generated by hbm2java
 */
@Entity
@Table(name = "Publication", catalog = "inmaa", uniqueConstraints = @UniqueConstraint(columnNames = "Publication_Name"))
public class Publication implements java.io.Serializable {

	private int publicationId;
	private String publicationName;
	private Date publicationDate;
	private String publicationLink;
	private String publicationUrl;
	private String publicationPicture;

	public Publication() {
	}

	public Publication(int publicationId, String publicationName,
			Date publicationDate, String publicationLink,
			String publicationPicture) {
		this.publicationId = publicationId;
		this.publicationName = publicationName;
		this.publicationDate = publicationDate;
		this.publicationLink = publicationLink;
		this.publicationPicture = publicationPicture;
	}

	public Publication(int publicationId, String publicationName,
			Date publicationDate, String publicationLink,
			String publicationUrl, String publicationPicture) {
		this.publicationId = publicationId;
		this.publicationName = publicationName;
		this.publicationDate = publicationDate;
		this.publicationLink = publicationLink;
		this.publicationUrl = publicationUrl;
		this.publicationPicture = publicationPicture;
	}

	@Id
	@Column(name = "Publication_Id", unique = true, nullable = false)
	public int getPublicationId() {
		return this.publicationId;
	}

	public void setPublicationId(int publicationId) {
		this.publicationId = publicationId;
	}

	@Column(name = "Publication_Name", unique = true, nullable = false, length = 45)
	public String getPublicationName() {
		return this.publicationName;
	}

	public void setPublicationName(String publicationName) {
		this.publicationName = publicationName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Publication_Date", nullable = false, length = 10)
	public Date getPublicationDate() {
		return this.publicationDate;
	}

	public void setPublicationDate(Date publicationDate) {
		this.publicationDate = publicationDate;
	}

	@Column(name = "Publication_Link", nullable = false, length = 225)
	public String getPublicationLink() {
		return this.publicationLink;
	}

	public void setPublicationLink(String publicationLink) {
		this.publicationLink = publicationLink;
	}

	@Column(name = "Publication_Url", length = 450)
	public String getPublicationUrl() {
		return this.publicationUrl;
	}

	public void setPublicationUrl(String publicationUrl) {
		this.publicationUrl = publicationUrl;
	}

	@Column(name = "Publication_Picture", nullable = false, length = 80)
	public String getPublicationPicture() {
		return this.publicationPicture;
	}

	public void setPublicationPicture(String publicationPicture) {
		this.publicationPicture = publicationPicture;
	}

}
